<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Download Full Report</name>
   <tag></tag>
   <elementGuidId>42857ab5-8370-4862-93ba-a5391d9ab17d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7811a772-e7ee-40dd-a7c3-2e52f174406e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-fit max-w-full rounded-full bg-tint-1 px-3 py-2 text-sm font-medium text-primary mt-4 hidden @3xl/section:grid</value>
      <webElementGuid>e3689344-f9aa-44d0-a128-36dc4591d2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc40bfc6-d76d-4057-b44d-dd7f74b8db97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>dd432afd-546f-40f2-9f98-50bd64d0f4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4be13988-6a9d-4c51-aefc-0b19c1649118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:Rec6fnjbta:</value>
      <webElementGuid>417efb8b-0201-49e0-9c5c-cf77d30569b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>8056582c-6669-40a2-afd4-f4567bc0f49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download Full Report</value>
      <webElementGuid>a68a4d82-383b-45bc-907b-5925165dd709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/div[@class=&quot;grid-full&quot;]/section[@class=&quot;grid @container/section grid-full relative gap-8&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;@container/section-content grid gap-8 grid-content @3xl/section:grid-cols-2 @3xl/section:gap-0&quot;]/div[@class=&quot;grid @3xl/section:items-center&quot;]/div[@class=&quot;relative max-w-full delay-200 duration-700 animate-in fade-in slide-in-from-bottom-6 @3xl/section:aspect-square @3xl/section:w-120 @3xl/section:rounded-full @3xl/section:bg-primary&quot;]/div[@class=&quot;grid place-content-center items-center gap-3 @3xl/section:absolute @3xl/section:inset-20&quot;]/button[@class=&quot;w-fit max-w-full rounded-full bg-tint-1 px-3 py-2 text-sm font-medium text-primary mt-4 hidden @3xl/section:grid&quot;]</value>
      <webElementGuid>5b6c8762-929a-49c1-9e90-e18eaf798b4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>7be7389d-97c2-4978-ad2f-279e500bd242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo Source: Unsplash'])[1]/following::button[1]</value>
      <webElementGuid>ac4787cf-855a-4b3a-9f16-6a2b04ba917f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Full Report'])[2]/preceding::button[1]</value>
      <webElementGuid>3b255272-8a99-48d7-ad14-772be4f468d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download Full Report']/parent::*</value>
      <webElementGuid>4a84c69a-f16a-4504-8df0-dbcbb7f4c056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5fe65c46-4137-412c-9de6-7292b83649e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Download Full Report' or . = 'Download Full Report')]</value>
      <webElementGuid>dc51d17d-f77c-4c4f-8a3c-1aa47f071814</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
