<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HIGO DIGITAL MANUAL 2024_phone</name>
   <tag></tag>
   <elementGuidId>f9dceed6-562f-439d-9669-0efc563ab50c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='phone'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eef2bf57-183c-4d2a-a7a3-5642e430ee1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-b border-white bg-transparent px-2 py-2 text-white outline-none placeholder:text-white/80</value>
      <webElementGuid>2aca8087-8f82-4ffe-bb67-f0efb3d82168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>328b0bbd-900d-4484-b58c-7b84a96d1ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-1p-ignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cb285408-fcad-41d6-b915-896062861e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>1d305967-bf5d-4ca1-aae0-7955a82853d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dec679b2-1b75-48c8-8f9c-d160206d3350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>755f2c83-7373-483e-b343-30b9262cb3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:Rec6fnjbta:&quot;)/form[@class=&quot;grid content-start gap-6 @container/form&quot;]/div[@class=&quot;grid grid-cols-1 gap-x-6 gap-y-6 @xl/form:grid-cols-2&quot;]/div[@class=&quot;grid grid-flow-row content-start gap-4&quot;]/input[@class=&quot;border-b border-white bg-transparent px-2 py-2 text-white outline-none placeholder:text-white/80&quot;]</value>
      <webElementGuid>d6ee1b4f-b5dc-4f0f-8966-cf916f7e1ac4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='phone'])[2]</value>
      <webElementGuid>3a7d5a6f-9513-441e-9cad-530fae16f386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:Rec6fnjbta:']/form/div[2]/div[4]/input</value>
      <webElementGuid>ce736b95-950d-4231-b6ae-639641e09a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/div[4]/input</value>
      <webElementGuid>418d6d6d-2e09-470c-afb4-3d1afe68a170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Phone Number' and @type = 'text' and @name = 'phone']</value>
      <webElementGuid>92169a71-2917-4c25-9e75-1cd50a613274</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
