<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kirim</name>
   <tag></tag>
   <elementGuidId>634524d5-029a-4a00-9617-d0301464a72f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b039aa23-6ddc-43b8-abb5-b27716f2f235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b271dad8-f169-4a33-9187-450e0c0c1c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full place-self-end rounded-full bg-primary px-3 py-1.5 text-white disabled:cursor-auto disabled:opacity-50 @2xl/section:mt-4 @2xl/section:w-fit @2xl/section:place-self-end @2xl/section:px-5 @2xl/section:py-3</value>
      <webElementGuid>6c64d222-2b24-4687-af3c-2dfcf001a3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim</value>
      <webElementGuid>d98c9b2f-8ec1-4432-aaf5-4836692ae6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_d5b9e1 font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/div[@class=&quot;grid min-h-screen grid-flow-row content-start gap-6 pt-safearea grid-content @3xl/page:pb-8&quot;]/div[@class=&quot;mb-20 grid content-start gap-10&quot;]/section[@class=&quot;grid grid-flow-row gap-4 @container/section&quot;]/form[@class=&quot;grid grid-flow-row gap-1 rounded-lg bg-gray-50 p-4&quot;]/button[@class=&quot;w-full place-self-end rounded-full bg-primary px-3 py-1.5 text-white disabled:cursor-auto disabled:opacity-50 @2xl/section:mt-4 @2xl/section:w-fit @2xl/section:place-self-end @2xl/section:px-5 @2xl/section:py-3&quot;]</value>
      <webElementGuid>4c2df9ab-6060-4664-ae8c-fe18a71585ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[8]</value>
      <webElementGuid>bb10456f-b850-4b64-bb0f-1367c537cfe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berikan Komentar'])[1]/following::button[1]</value>
      <webElementGuid>5923de80-4013-4a3a-a2f9-1c927b51b528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bangga'])[1]/following::button[1]</value>
      <webElementGuid>05fa3072-d617-4c34-9145-007b5c0f4e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/preceding::button[1]</value>
      <webElementGuid>2cf5003e-2f75-4aa4-bce8-9a5ea5fdaf3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today at 7:00 AM'])[1]/preceding::button[1]</value>
      <webElementGuid>9690e3e8-74ac-4463-bda0-326da868b755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kirim']/parent::*</value>
      <webElementGuid>64ad32c1-95c2-4b8a-bfba-df964fb64d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/form/button</value>
      <webElementGuid>66e2e14a-7bdc-4269-adfc-9e67cb91203f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Kirim' or . = 'Kirim')]</value>
      <webElementGuid>ad49ccef-e4b6-4e1d-a9df-d5ffa444017b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/following::button[1]</value>
      <webElementGuid>84b9e4fc-0220-49ab-af91-99baaef97d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tes'])[1]/preceding::button[1]</value>
      <webElementGuid>20140184-3d83-44dd-b646-602c9507a334</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
