<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Berikan Komentar_name</name>
   <tag></tag>
   <elementGuidId>4b0f3382-e519-4c84-941a-6aa823ada151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21a895cd-5032-46fc-995d-b85e1b0a4633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Nama Kamu</value>
      <webElementGuid>c0542429-f6f6-410d-a011-af7b07dbf6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-md bg-gray-100 px-2.5 py-2 focus:bg-white</value>
      <webElementGuid>ca684a0a-a524-4ed1-8923-d954e8893967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b79fa86-b01b-493a-b9aa-34093fd9e946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>442b17c7-3b8b-422a-a4c1-59836caa962a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_d5b9e1 font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/div[@class=&quot;grid min-h-screen grid-flow-row content-start gap-6 pt-safearea grid-content @3xl/page:pb-8&quot;]/div[@class=&quot;mb-20 grid content-start gap-10&quot;]/section[@class=&quot;grid grid-flow-row gap-4 @container/section&quot;]/form[@class=&quot;grid grid-flow-row gap-1 rounded-lg bg-gray-50 p-4&quot;]/div[@class=&quot;grid grid-flow-row gap-1&quot;]/input[@class=&quot;rounded-md bg-gray-100 px-2.5 py-2 focus:bg-white&quot;]</value>
      <webElementGuid>9ae58a1a-207c-44cd-b522-e5df8d2a32a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name']</value>
      <webElementGuid>e157c072-e37f-4152-a1c4-9f8afafde3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>b8933b33-a1ad-4ea1-99dc-be8919265e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tulis Nama Kamu' and @type = 'text' and @name = 'name']</value>
      <webElementGuid>7a9c5a81-0164-47b9-a168-13d4477e8a5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
