<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_test</name>
   <tag></tag>
   <elementGuidId>44cc5f5b-c3b4-4a66-b954-ae1b3e4e9f74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='comment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;comment&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c6a0d15d-2e25-4fb1-a912-830106288526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comment</value>
      <webElementGuid>4b421712-a61b-4a79-8a12-1c4b989dccbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Komentar Kamu</value>
      <webElementGuid>d64c4e66-2aef-4ae2-960c-ded624a3e36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>min-h-24 rounded-md bg-gray-100 px-2.5 py-2 focus:bg-white</value>
      <webElementGuid>bb2b4d0d-c2ca-45c7-b332-de2f5df1bf76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>fccfe057-2dc1-400a-9b10-eb5767866118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_d5b9e1 font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/div[@class=&quot;grid min-h-screen grid-flow-row content-start gap-6 pt-safearea grid-content @3xl/page:pb-8&quot;]/div[@class=&quot;mb-20 grid content-start gap-10&quot;]/section[@class=&quot;grid grid-flow-row gap-4 @container/section&quot;]/form[@class=&quot;grid grid-flow-row gap-1 rounded-lg bg-gray-50 p-4&quot;]/div[@class=&quot;grid grid-flow-row gap-1&quot;]/textarea[@class=&quot;min-h-24 rounded-md bg-gray-100 px-2.5 py-2 focus:bg-white&quot;]</value>
      <webElementGuid>d7bb57aa-9d7f-42d6-8722-cf9a270fa328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='comment']</value>
      <webElementGuid>38a83cc7-fee7-4976-a692-5c53cf801f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berikan Komentar'])[1]/following::textarea[1]</value>
      <webElementGuid>429fc9f1-6622-4c7c-9f2b-356ff6a2ba0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bangga'])[1]/following::textarea[1]</value>
      <webElementGuid>4cce9523-b54b-4d3d-bb36-881df805f6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/preceding::textarea[1]</value>
      <webElementGuid>527ca1fd-d6a7-4f75-8f23-1d5da1a2f7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tes'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8992d44a-ed2c-4b81-80b8-628330427725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test']/parent::*</value>
      <webElementGuid>6b5b6bfc-5610-46db-81b9-db61ddf7f6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ee4fff7e-3d2f-455b-bc82-4b0e099535d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'comment' and @placeholder = 'Tulis Komentar Kamu' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>84cb5d7c-8af1-4656-bc08-c62f509a3b7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
