<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pencarian_q</name>
   <tag></tag>
   <elementGuidId>c5977e49-636c-40ce-855b-16ec8ba2f43a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='q']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;q&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15efe7e8-d743-4c51-bb7c-cece8dcb1dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full rounded-full border px-2.5 py-1.5 text-sm disabled:animate-pulse disabled:bg-gray-100</value>
      <webElementGuid>a1b546fb-05c4-4a32-9092-3b32e66359b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Artikel</value>
      <webElementGuid>32e3baeb-b18c-4748-acde-a1f8e67872f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1f829d05-e0cd-4706-9ab7-a43560a6209a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tips Bisnis</value>
      <webElementGuid>63f08c87-6ca2-4c19-8097-054b81ce0c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>bf8e4973-0d09-40b3-a902-c0a08411502f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_d5b9e1 font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/div[@class=&quot;min-h-screen-3/4 content-start gap-4 py-safearea grid-content-container @7xl/page:gap-0&quot;]/div[@class=&quot;grid-narrow&quot;]/section[@class=&quot;grid content-start gap-8 @container/section&quot;]/form[@class=&quot;relative&quot;]/input[@class=&quot;w-full rounded-full border px-2.5 py-1.5 text-sm disabled:animate-pulse disabled:bg-gray-100&quot;]</value>
      <webElementGuid>cf0bc120-ad19-45b1-afbb-ffc52a4ad9fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='q']</value>
      <webElementGuid>82960f24-ffc3-467b-aa08-a0bc8380f508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>8be0c112-d652-4a86-92e0-bf023f9f2429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Cari Artikel' and @name = 'q']</value>
      <webElementGuid>fd214b00-6eb2-4388-aee5-6f5109c9e980</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
