<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_All</name>
   <tag></tag>
   <elementGuidId>25e3a849-6846-4939-8e5b-0c66e32e3982</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5adf5c28-2bed-4ee4-8028-18522f1c4867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid w-full grid-flow-col place-content-start place-items-center gap-1.5 rounded-full border border-primary px-2 py-1</value>
      <webElementGuid>b8b27a28-884e-4ac8-9f68-9987b9209cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16479f7d-fc75-40de-9c66-a0a791b76267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>8208853c-8a79-448c-b55f-df0e2832e0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e71b60a6-e9c3-46d6-9ae0-047a2d050017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r0:</value>
      <webElementGuid>c0fc5bdc-48b5-45cc-ac3b-9fd72a2d21cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>a2d09b1d-5a56-4897-9e55-4a7981d2e9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>e962af44-1c73-4442-a5b7-bf55cfc7c3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/section[@class=&quot;grid gap-y-10 @container/section grid-compact @2xl/page:pt-30 my-10 mt-0 py-20 @2xl/page:pb-20&quot;]/div[@class=&quot;grid divide-y overflow-clip rounded-md border @2xl/section:grid-cols-2 @2xl/section:divide-x @2xl/section:divide-y-0 @4xl/section:grid-cols-3&quot;]/div[@class=&quot;col-span-1 grid max-h-148 grid-rows-[auto_auto_1fr] divide-y&quot;]/header[@class=&quot;grid gap-2 p-2&quot;]/button[@class=&quot;grid w-full grid-flow-col place-content-start place-items-center gap-1.5 rounded-full border border-primary px-2 py-1&quot;]</value>
      <webElementGuid>dd18d07a-5ffd-426a-9e3c-43e2444ddb14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>60a6d669-76f3-4bd3-b4a1-96e2b038981d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Kotamu'])[1]/following::button[1]</value>
      <webElementGuid>83481e63-b7c3-40fb-8d9b-bfc6a36e97b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jelajahi lokasi HIGOspot'])[1]/following::button[1]</value>
      <webElementGuid>217ba157-0313-42e5-a1e5-f98031d17537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cafe/Coffee Shop'])[2]/preceding::button[1]</value>
      <webElementGuid>837cb8dc-b529-46ab-ac18-0f71b7a5017a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/button</value>
      <webElementGuid>f455997c-0ca7-48a6-b759-735f11a12b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'All' or . = 'All')]</value>
      <webElementGuid>9db8745a-12cf-4e0c-b452-253a68e8fd0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
