<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_HIGOspot</name>
   <tag></tag>
   <elementGuidId>6bd21a20-7d5a-4cff-9d7d-4dcfc931ebf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[2]/following::h1[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ea7b4052-e5d4-443b-a5a8-fc2049b3e6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>@2xl/page: z-10 font-anek-malayalam text-4.5xl font-bold leading-none text-white duration-700 animate-in fade-in slide-in-from-bottom-6 @2xl/page:text-6xl</value>
      <webElementGuid>3d910e25-c0a8-4b32-be20-758304c85353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HIGOspot</value>
      <webElementGuid>efc1f6f8-3321-4a33-b90c-284f752dba2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/section[@class=&quot;grid @container/section grid-full min-h-148 @2xl/page:h-screen-4/5 @2xl/page:max-h-164 mt-safearea&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;z-30 row-start-2 grid content-center items-center gap-4 place-self-center px-6 py-16 col-start-content col-end-content @2xl/page:row-start-1 @2xl/page:px-16 @2xl/page:col-end-none&quot;]/h1[@class=&quot;@2xl/page: z-10 font-anek-malayalam text-4.5xl font-bold leading-none text-white duration-700 animate-in fade-in slide-in-from-bottom-6 @2xl/page:text-6xl&quot;]</value>
      <webElementGuid>2817f792-9678-457d-b419-d337219ced06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[2]/following::h1[1]</value>
      <webElementGuid>faca2ece-511a-4f00-88cb-3c99bc37ebe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::h1[1]</value>
      <webElementGuid>f5e71d93-f66c-480a-afce-66ca460fc01f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tetap terhubung dengan pelanggan'])[1]/preceding::h1[1]</value>
      <webElementGuid>ab02b380-648b-4d33-b1d2-a86d992c7b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kenali pengunjung lewat dashboard'])[1]/preceding::h1[1]</value>
      <webElementGuid>2b9696a8-8c18-4408-983a-1cea66624c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>bd6f5fee-85a4-4c52-ad48-af78aaf82a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'HIGOspot' or . = 'HIGOspot')]</value>
      <webElementGuid>4da30ced-a1e2-4843-9602-82801ceb44da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
