<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apa saja layanan HIGO Apakah hanya m_fecf51</name>
   <tag></tag>
   <elementGuidId>f6ff6f31-ee0b-4053-a5f4-5822358fc8b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-:R6qfjbta:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5c768c7-af66-454e-8921-395ce73deb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5388cbb0-fd4e-49bf-a3aa-bd79510c63cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:R16qfjbta:</value>
      <webElementGuid>0f315837-34b3-4424-aab3-f7ce6e268fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c1f6ac0-40ca-46b7-935c-6e196c290bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>563c0db4-edb1-4e2b-a550-86cce9590a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>93795c93-813c-4e6c-b81a-96d6b313d2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:R6qfjbta:</value>
      <webElementGuid>199851b0-a86e-4b18-b8c1-60dd69ad4672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-1 items-center justify-between py-4 transition-all [&amp;[data-state=open]>svg]:rotate-180 text-left text-base font-bold text-primary @2xl/page:text-lg</value>
      <webElementGuid>9859b894-ffd0-4f44-b032-1755aff2c5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apa saja layanan HIGO? Apakah hanya menyediakan WiFi Advertising dan Marketing saja?</value>
      <webElementGuid>106e74a8-b405-4a05-a490-98f6a89c8703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:R6qfjbta:&quot;)</value>
      <webElementGuid>4e4ec71d-dc72-420e-804c-4b34f0f45040</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='radix-:R6qfjbta:']</value>
      <webElementGuid>de82534e-4bcf-4a20-a3e6-de6ba87e7f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pertanyaan seputar HIGO'])[1]/following::button[1]</value>
      <webElementGuid>4c1a6d83-acc7-42c6-9fc0-ba3ff43c8956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partner &amp; klien'])[1]/following::button[1]</value>
      <webElementGuid>8f33e645-b03f-4e2a-94f2-602db819e4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dimana saya bisa melihat perkiraan harga jika saya ingin bekerjasama dengan HIGO?'])[1]/preceding::button[1]</value>
      <webElementGuid>c63a4c0c-0d27-4286-a9e8-413670820d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HIGO itu ISP ya?'])[1]/preceding::button[3]</value>
      <webElementGuid>2e3bfcb7-65a8-43ef-b8e3-cdcd89c877ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apa saja layanan HIGO? Apakah hanya menyediakan WiFi Advertising dan Marketing saja?']/parent::*</value>
      <webElementGuid>77159079-0d3d-4be7-9d6d-3932fda44432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/button</value>
      <webElementGuid>d9594737-a172-4f09-9dfd-6f0882c14d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radix-:R6qfjbta:' and (text() = 'Apa saja layanan HIGO? Apakah hanya menyediakan WiFi Advertising dan Marketing saja?' or . = 'Apa saja layanan HIGO? Apakah hanya menyediakan WiFi Advertising dan Marketing saja?')]</value>
      <webElementGuid>938cf2fb-026d-4cc8-b440-ff9541c7b56a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
