<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Pelajari lebih lanjut_size-full rounded-lg bg-transparent object-cover</name>
   <tag></tag>
   <elementGuidId>7d9f4b34-fa58-46df-8394-4214fa2ab99e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='HIGOspot']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e609c14b-9d59-4a09-862d-9044e90c8251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>HIGOspot</value>
      <webElementGuid>ad7f510e-b10b-426b-b76b-822a0b692fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>ec9d7c8b-6841-4edb-bfcd-c446ab9486b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>9f4c52f5-df92-42ed-aee6-7cb7309a5e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>d9611279-cf7c-47a1-950a-3b908f563714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>90a11373-f35f-4c5e-aad8-05d229b36594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>de3ddbd1-ab2b-4750-9bb3-3d80a819d13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>size-full rounded-lg bg-transparent object-cover</value>
      <webElementGuid>febccbaf-0b3e-40f3-aff5-e6798c32dad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>3999f93d-9e5f-4122-9d96-1d297c19a347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=16&amp;q=75 16w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=32&amp;q=75 32w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=48&amp;q=75 48w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=64&amp;q=75 64w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=96&amp;q=75 96w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=128&amp;q=75 128w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=256&amp;q=75 256w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=384&amp;q=75 384w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=640&amp;q=75 640w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=750&amp;q=75 750w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=828&amp;q=75 828w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=1080&amp;q=75 1080w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=1200&amp;q=75 1200w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=1920&amp;q=75 1920w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=2048&amp;q=75 2048w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>31e7fb37-0bbe-4006-a1ed-b22efaf9891b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=3840&amp;q=75</value>
      <webElementGuid>d4c2857c-861a-4ddc-9565-ab47cbabaa22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/section[@class=&quot;gap-y-14 py-20 grid-full-container @xl/page:py-32 @2xl/page:py-36&quot;]/div[@class=&quot;relative grid-full @3xl/page:grid-narrow&quot;]/div[@class=&quot;overflow-hidden&quot;]/div[@class=&quot;flex mx-4 @3xl/page:mx-0 @3xl/page:!translate-x-0&quot;]/div[@class=&quot;min-w-0 shrink-0 grow-0 pl-4 basis-11/12 @3xl/page:basis-1/3&quot;]/a[@class=&quot;group/card relative grid min-h-80 cursor-pointer place-content-end gap-4 overflow-clip rounded-lg transition-all @3xl/page:min-h-96 @3xl/page:hover:rounded-2xl&quot;]/div[@class=&quot;absolute inset-0&quot;]/img[@class=&quot;size-full rounded-lg bg-transparent object-cover&quot;]</value>
      <webElementGuid>f4722cf6-48c2-496b-8aed-6ad722336268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='HIGOspot']</value>
      <webElementGuid>5f7fb8b4-8f59-41b9-8794-f3f28d922ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div[2]/img</value>
      <webElementGuid>81bc12bf-0e36-46de-95f4-fe1e598aeff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'HIGOspot' and @src = '/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-higospot.65b05c41.jpg&amp;w=3840&amp;q=75']</value>
      <webElementGuid>51103d8c-9e3f-4c84-9c84-44efd6dac898</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
