<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Pelajari lebih lanjut_size-full rounded-lg bg-transparent object-cover agent</name>
   <tag></tag>
   <elementGuidId>1ccf25c0-8e49-4aa5-b68f-420c8af6cae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Integrated Digital Agency']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>92a38ee6-5297-450e-9c35-bed8e6338d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Integrated Digital Agency</value>
      <webElementGuid>faebb41b-2652-42e7-97e8-613c5e6772b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>28823008-484f-4fbe-afe2-1dfaadaf31d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>c199909c-5ef6-4a50-93f4-e843458b3757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>f4449253-d5fd-48ef-bff4-08d9b0f25857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>0b9c3975-f3b6-4360-96fe-c3ad78ca5b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5bf40bd8-36e4-407f-af68-d69bf5f9d455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>size-full rounded-lg bg-transparent object-cover</value>
      <webElementGuid>26099f94-f284-4c06-8f63-7c4d4f07eb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>170737b7-3e9b-4215-8528-fb4a9eaf6d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=16&amp;q=75 16w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=32&amp;q=75 32w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=48&amp;q=75 48w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=64&amp;q=75 64w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=96&amp;q=75 96w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=128&amp;q=75 128w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=256&amp;q=75 256w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=384&amp;q=75 384w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=640&amp;q=75 640w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=750&amp;q=75 750w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=828&amp;q=75 828w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=1080&amp;q=75 1080w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=1200&amp;q=75 1200w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=1920&amp;q=75 1920w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=2048&amp;q=75 2048w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>5a1fd510-06e0-45ed-a30f-de67265dea52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=3840&amp;q=75</value>
      <webElementGuid>3ab5f263-abd6-4068-bedb-5d2357f05b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/section[@class=&quot;gap-y-14 py-20 grid-full-container @xl/page:py-32 @2xl/page:py-36&quot;]/div[@class=&quot;relative grid-full @3xl/page:grid-narrow&quot;]/div[@class=&quot;overflow-hidden&quot;]/div[@class=&quot;flex mx-4 @3xl/page:mx-0 @3xl/page:!translate-x-0&quot;]/div[@class=&quot;min-w-0 shrink-0 grow-0 pl-4 basis-11/12 @3xl/page:basis-1/3&quot;]/a[@class=&quot;group/card relative grid min-h-80 cursor-pointer place-content-end gap-4 overflow-clip rounded-lg transition-all @3xl/page:min-h-96 @3xl/page:hover:rounded-2xl&quot;]/div[@class=&quot;absolute inset-0&quot;]/img[@class=&quot;size-full rounded-lg bg-transparent object-cover&quot;]</value>
      <webElementGuid>eba3e27c-a83b-4285-821b-0efdb4c8f51e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Integrated Digital Agency']</value>
      <webElementGuid>bde3cc35-d289-4496-813d-a82ffc4a05c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div[2]/img</value>
      <webElementGuid>d9a6c930-6d47-4884-9f2a-c23f216b1e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Integrated Digital Agency' and @src = '/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-digital-agency.a4475022.png&amp;w=3840&amp;q=75']</value>
      <webElementGuid>7880d2ba-9a22-47e7-922f-fb994bf992ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
