<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_HIGO_size-full rounded-lg bg-transparent object-cover</name>
   <tag></tag>
   <elementGuidId>d1bf6b5e-51d1-4176-a168-bb39134a70a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='WiFi Advertising']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.size-full.rounded-lg.bg-transparent.object-cover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>db9b867a-ede1-495e-ba03-a4ed15393f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>WiFi Advertising</value>
      <webElementGuid>fb1ab643-1612-438b-a6c7-7473fdb1704f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>55c39e02-c718-43d8-8cb5-315119e27d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>cd4704d4-4d20-4c5a-8f4f-2d819a5dfa03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>463bb2e7-16ea-4aac-a33e-0f3894263f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>043eba8c-64de-4ce8-aff1-2ddd4596d756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cad3c6e4-c4a9-4b1f-9809-bef3af2db21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>size-full rounded-lg bg-transparent object-cover</value>
      <webElementGuid>4530df70-29b2-4fbb-ad3a-9955880c237d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>38719665-9051-435d-89f8-c3da107eebe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=16&amp;q=75 16w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=32&amp;q=75 32w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=48&amp;q=75 48w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=64&amp;q=75 64w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=96&amp;q=75 96w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=128&amp;q=75 128w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=256&amp;q=75 256w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=384&amp;q=75 384w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=640&amp;q=75 640w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=750&amp;q=75 750w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=828&amp;q=75 828w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=1080&amp;q=75 1080w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=1200&amp;q=75 1200w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=1920&amp;q=75 1920w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=2048&amp;q=75 2048w, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>99a2e302-b0d2-49b4-a457-978a139d6919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=3840&amp;q=75</value>
      <webElementGuid>c150d21d-b1e5-4080-925f-a94557878aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/section[@class=&quot;gap-y-14 py-20 grid-full-container @xl/page:py-32 @2xl/page:py-36&quot;]/div[@class=&quot;relative grid-full @3xl/page:grid-narrow&quot;]/div[@class=&quot;overflow-hidden&quot;]/div[@class=&quot;flex mx-4 @3xl/page:mx-0 @3xl/page:!translate-x-0&quot;]/div[@class=&quot;min-w-0 shrink-0 grow-0 basis-11/12 pl-0 @3xl/page:basis-1/3&quot;]/a[@class=&quot;group/card relative grid min-h-80 cursor-pointer place-content-end gap-4 overflow-clip rounded-lg transition-all @3xl/page:min-h-96 @3xl/page:hover:rounded-2xl&quot;]/div[@class=&quot;absolute inset-0&quot;]/img[@class=&quot;size-full rounded-lg bg-transparent object-cover&quot;]</value>
      <webElementGuid>26b52b15-15d2-4363-9212-bb04ae94e610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='WiFi Advertising']</value>
      <webElementGuid>6b783cd1-2417-4e63-bb49-d2f6f2e35c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/img</value>
      <webElementGuid>4fe9e526-68da-4c26-a027-ed60880c503c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'WiFi Advertising' and @src = '/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Four-service-wifi-ads.adb3ed09.jpg&amp;w=3840&amp;q=75']</value>
      <webElementGuid>4defc61d-74c5-4514-9173-a3c3095ca13a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
