<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_HIGOspotIntegrated Digital AgencyWiF_18ac72</name>
   <tag></tag>
   <elementGuidId>eacb9e5b-5df5-467b-b192-757df23f71dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='service']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;service&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>26d89ad9-1328-48ca-9ee0-b53eb4591130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>service</value>
      <webElementGuid>e746e878-2fa3-46ec-b9d7-10383bebd8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full appearance-none rounded border px-2.5 py-1.5 text-sm</value>
      <webElementGuid>3fbd4665-416d-484d-9146-f870f364ea64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HIGOspotIntegrated Digital AgencyWiFi Advertising</value>
      <webElementGuid>4ae77791-06df-41d6-b244-be7db400ba24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/div[@class=&quot;grid gap-6 pt-safearea grid-content @4xl/page:grid-cols-2 @4xl/page:pb-safearea @4xl/page:pt-safearea-2x&quot;]/section[@class=&quot;grid&quot;]/div[@class=&quot;grid min-h-96 content-start gap-4 rounded-3xl bg-white p-6&quot;]/form[@class=&quot;grid gap-4&quot;]/div[@class=&quot;grid grid-flow-row gap-1&quot;]/div[@class=&quot;relative&quot;]/select[@class=&quot;w-full appearance-none rounded border px-2.5 py-1.5 text-sm&quot;]</value>
      <webElementGuid>6b9b516d-8de2-4f2a-93ac-cc9c231ad5ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='service']</value>
      <webElementGuid>9f60ef51-eae8-455b-a3ca-b9e1d8473c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan yang ingin ditanyakan'])[1]/following::select[1]</value>
      <webElementGuid>66834c20-9c32-4695-8355-9dc909ea7b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama perusahaan/lokasi/event/brand'])[1]/following::select[1]</value>
      <webElementGuid>0d8d94e5-25cd-48bd-ae04-55d3ab5f63e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan'])[1]/preceding::select[1]</value>
      <webElementGuid>86c8ad4e-82f1-4537-a947-f56f852fe1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[1]</value>
      <webElementGuid>8f12ac61-fcde-401e-970f-9e19a6e186a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c91f84de-536a-44f4-abef-52bba69dd8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'service' and (text() = 'HIGOspotIntegrated Digital AgencyWiFi Advertising' or . = 'HIGOspotIntegrated Digital AgencyWiFi Advertising')]</value>
      <webElementGuid>6b089c60-4671-43d6-b735-7a4fb24e3c54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
