<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_test</name>
   <tag></tag>
   <elementGuidId>bfcaee76-d6e3-42b6-b7f0-74959b1aaffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;message&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f64396cd-4e16-42a3-98a9-5bf9a523cf34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>564a0f6d-7bae-4730-8b3a-a0bebd12d45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis pesan kamu</value>
      <webElementGuid>64450fb1-c678-4f22-b7f3-b16908eeed6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded border px-2.5 py-1.5 text-sm resize-none h-60</value>
      <webElementGuid>2e34ae69-15b6-4d68-ae38-0cb131afb7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>959017a9-bf86-4118-8540-d96dae16cb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/div[@class=&quot;grid gap-6 pt-safearea grid-content @4xl/page:grid-cols-2 @4xl/page:pb-safearea @4xl/page:pt-safearea-2x&quot;]/section[@class=&quot;grid&quot;]/div[@class=&quot;grid min-h-96 content-start gap-4 rounded-3xl bg-white p-6&quot;]/form[@class=&quot;grid gap-4&quot;]/div[@class=&quot;grid grid-flow-row gap-1&quot;]/textarea[@class=&quot;rounded border px-2.5 py-1.5 text-sm resize-none h-60&quot;]</value>
      <webElementGuid>d895af47-5a56-46b6-897a-fb242b75c9ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='message']</value>
      <webElementGuid>c4d1d5cb-25d1-4778-a7f5-d8a0dd1764cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan'])[1]/following::textarea[1]</value>
      <webElementGuid>0f1c9d3c-85bf-4291-9d04-03569d833729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan yang ingin ditanyakan'])[1]/following::textarea[1]</value>
      <webElementGuid>fa0e01b0-95a6-407b-9724-989861583c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e5f6ac18-a73f-4cd6-ad2e-7b1a2f4cc198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT HIGO FITUR INDONESIA'])[1]/preceding::textarea[1]</value>
      <webElementGuid>7a6974f9-8c3c-4b08-9f13-f73a1c07a521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test']/parent::*</value>
      <webElementGuid>34c8310a-a87f-414a-9952-f1eeeb145c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f494bcac-cbd5-42e0-8bdd-d20fc57835a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'message' and @placeholder = 'Tulis pesan kamu' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>64e193ed-ee90-40c5-84f2-da28d1a66818</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
