<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_tes</name>
   <tag></tag>
   <elementGuidId>c3453725-7a56-43ee-8aa2-460c297df4f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;message&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4e7565cb-bd3c-4d55-bea1-6f094349faf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>7619c049-7f1f-4357-90e0-d8826755a954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis pesan kamu</value>
      <webElementGuid>b1146e74-d967-4260-b771-09ff0f586760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded border px-2.5 py-1.5 text-sm resize-none h-60</value>
      <webElementGuid>e9b6c740-e381-4f37-955b-84986d4db517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tes</value>
      <webElementGuid>ecf59d70-ed76-4ceb-8a61-9b3515378bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/div[@class=&quot;grid gap-6 pt-safearea grid-content @4xl/page:grid-cols-2 @4xl/page:pb-safearea @4xl/page:pt-safearea-2x&quot;]/section[@class=&quot;grid&quot;]/div[@class=&quot;grid min-h-96 content-start gap-4 rounded-3xl bg-white p-6&quot;]/form[@class=&quot;grid gap-4&quot;]/div[@class=&quot;grid grid-flow-row gap-1&quot;]/textarea[@class=&quot;rounded border px-2.5 py-1.5 text-sm resize-none h-60&quot;]</value>
      <webElementGuid>e7ec2f56-d384-439e-ab7c-e93037330336</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='message']</value>
      <webElementGuid>4ff9a11d-62e9-48b6-a051-8d52c31d04ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan'])[1]/following::textarea[1]</value>
      <webElementGuid>bd845c8e-648a-48ec-be19-7a140c18115b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan yang ingin ditanyakan'])[1]/following::textarea[1]</value>
      <webElementGuid>0036953e-c414-449f-8f0a-3eb3ad324ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>289063cc-6772-4abe-93ba-0705aca80f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT HIGO FITUR INDONESIA'])[1]/preceding::textarea[1]</value>
      <webElementGuid>23c72532-fefa-46fb-aad6-b8d50c5e7609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='tes']/parent::*</value>
      <webElementGuid>07a2ea63-ce07-45d0-a7f9-0fff9e851826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a4166c5c-4f92-441c-81d4-09640eb8cda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'message' and @placeholder = 'Tulis pesan kamu' and (text() = 'tes' or . = 'tes')]</value>
      <webElementGuid>a5f4c5dd-5055-469c-a0ef-53bb777f76fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
